import image from "../assets/Images/image.jpg";
export const itemList = [
  {
    id: 1,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 2,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 3,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 4,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 5,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 6,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 7,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 8,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 9,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 10,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 11,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 12,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 13,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 14,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 15,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 16,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
  {
    id: 17,
    image: image,
    name: "پاستا بادمجان",
    time: "25-15",
    keywords: ["گیاهی", "پاستا", "گیلکی"],
    rating: "4.5(25+)",
  },
];

export const filterList = [
  {
    name: "دسته بندی غذایی",
    types: [
      "خوارک گوشت",
      "خوارک حبوبات",
      "چوجه کباب",
      " بورانی",
      "پیش غذا,",
      "کوفته - کبه",
      "دسر",
      "کیک",
      "دریایی",
      "آش",
      "سوپ",
      "خورشت",
      "کباب",
      "پاستا",
      "گراتن",
      "پیتزا",
    ],
  },
  {
    name: "روش پخت",
    types: [
      "جوشاندن",
      "باربکیو یا منقل",
      "آرام پز",
      "مخلوط کردن",
      "تف دادن",
      "گریل کردن",
      "پخت با فر",
    ],
  },
  {
    name: "مزه",
    types: ["ادویه ای", "ملس", "ترش", "نرمال"],
  },
];

export const sortList = [
  { id: 1, name: "جدیدترین" },
  { id: 2, name: "یمی ترین" },
  { id: 3, name: "بوب ترین" },
  { id: 4, name: "یگان" },
];
